# Generated by Django 5.2 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_no', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=20)),
                ('passenger_name', models.TextField()),
                ('contact_data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_conditions', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ticket flight',
                'verbose_name_plural': 'Ticket flights',
                'db_table': 'ticket_flights',
                'managed': False,
            },
        ),
    ]
